services:

  postgres:
    image: postgres:16
    container_name: conecta_comunidade_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${KEY_POSTGRES_DB}
      POSTGRES_USER: ${KEY_POSTGRES_NAME}
      POSTGRES_PASSWORD: ${KEY_POSTGRES_PASSWORD}

    ports:
      - "${KEY_POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: